
name: CI-CD Pipeline for Real Estate Prediction


on:
  
  push:
    branches:
      - main
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/realestateprediction


jobs:
  
  build-and-train:
    
    runs-on: ubuntu-latest 

    
    steps:
    - name: Check out the code
      
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (from shopping list)
      
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt
    
    - name: Run the full training pipeline
      
      run: |
        python main.py

    
    - name: Upload Training Artifacts
      
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        
        path: artifacts/

  build-and-push-docker:
  
    needs: build-and-train
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: trained-model-artifacts
        path: artifacts/
        
    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  
        file: ./Dockerfile 
        tags: ${{ env.IMAGE_NAME }}:latest